basePath: /api/v1
definitions:
  models.Recipe:
    properties:
      id:
        type: string
      ingredients:
        items:
          type: string
        type: array
      instructions:
        items:
          type: string
        type: array
      name:
        type: string
      publishedAt:
        type: string
      tags:
        items:
          type: string
        type: array
    type: object
externalDocs:
  description: OpenAPI
  url: https://bramworks.com/resources/open-api/
host: localhost:8080
info:
  contact:
    email: support@bramworks.com
    name: API Support
    url: https://bramworks.com/support
  description: This is a sample server celler server.
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: https://bramworks.com/terms/
  title: Recipes Example API
  version: "1.0"
paths:
  /recipes:
    get:
      consumes:
      - application/json
      description: recipes list
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Recipe'
      summary: Return a recipes list
      tags:
      - recipes
swagger: "2.0"
